total_steps: 20000
dqfd_pretrain_steps: 10000
discrete: False
max_steps_per_traj: 1000

sac: { learning_starts: 10000, use_sde: false }

td3: { learning_starts: 10000 }

cluster_config:
  {
    cluster_type: "kmeans",
    agglomerative_clustering_kwargs:
      { metric: "l2", linkage: "average", distance_threshold: 2.5 },
    kmeans_clustering_kwargs:
      { n_clusters: 500, max_iter: 300, algorithm: "lloyd" },
  }

prune_config:
  {
    prune_type: "action",
    group_filtering_kwargs:
      { size_threshold: 3, measure_cutoff: 80, method: "entropy" },
    action_filtering_kwargs:
      {
        size_threshold: 10,
        measure_cutoff: 80,
        method: "entropy",
        percentile: 80,
      },
    outcome_filtering_kwargs: { horizon: 10 },
  }
